name: flask-digit-identifier

# nomkl is needed to avoid issues deploying to Heroku
dependencies:
  - nomkl
  - flask==1.1.1
  - keras==2.3.1
  - Pillow==6.2.0
  - numpy==1.16.4
  - gunicorn==19.9.0
  # Heroku can't find 3.10.1
  - protobuf==3.10.0
